[package]
name = "pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ingest = { path = "../ingest" }
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.eframe]
version = "0.22"
default-features = false
features = ["default_fonts", "glow", "wayland"]
