[package]
name = "sysinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.27", features = ["uio", "resource", "fs"] }
tracing = "0.1"
util = { path = "../util" }
